image: eicweb.phy.anl.gov:4567/containers/image_recipes/ubuntu_dind:latest
#

simc_singularity:
  script:
     - cp containers/singularity/Singularity Singularity.simc
     - /bin/bash .gitlabci/build.sh Singularity.simc
     - mkdir -p build 
     - cp Singularity.simc.simg build/.
     - cp Singularity.simc build/.

  # This is where you can save job artifacts
  # https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html
  # You can specify the path to containers or the build folder to save.
  # Don't forget to save your recipes too!
  artifacts:
      paths:
        - build/Singularity.simc.simg
        - build/Singularity.simc
