#!/usr/bin/python

import tempfile
import os
import subprocess

with tempfile.TemporaryDirectory() as tmpdir:
    print('created directory', tmpdir)
    os.chdir(tmpdir)
    path = '/Users/sly2j/Dropbox/Work/Tools/simc/share/simc/data/'
    for file in os.listdir(path):
        os.symlink(path+file, file)
    os.symlink(path+'../../../BUILD/head/simc/simc', 'simc')
    for file in os.listdir(tmpdir):
        print(file)
    os.chmod
    subprocess.call(['./simc'])

